### PR TITLE
FS2-2679: Pass axis line settings

### PR DESCRIPTION
**Pull request by JustinCCYap**

### CODE REVIEW

**Comment by chschan** [comment]
While you are at it, maybe you could also expose `.axis.grid.dash` and `.axis.zero.line.dash`? It not exposed in the plugins code, but I users might want to change it, especially as the current default is for the zero line to be dashed which is different from the bar/column etc charts

**Comment by JustinCCYap** [comment]
Showing the zero line is not an option with scatterplots, only the axis line, is that correct?

**Comment by chschan** [comment]
In the current plugins code, it is an option on the Values (Y) axis, but we might need to change that.

**Comment by JustinCCYap** [comment]
I see. OK

**Review by chschan — APPROVED** [review]

**Pull request merged**
