### PR TITLE
RS-15014: fix ticklabel format

### PR DESCRIPTION
**Pull request by chschan**

### CODE REVIEW

**Review by jrwishart — APPROVED** [review]

**Comment by mwmclean** [comment]
@chschan I'm testing this out on reusdev now and still seeing the scientific notation in the blog project.

**Comment by chschan** [comment]
Thanks @mwmclean. Can you try it again now?

**Comment by jrwishart** [comment]
When I tested it earlier, it still gave scientific notation on `prod` and the test has been diffing between the two situations over the last week.

**Comment by jrwishart** [comment]
Checked diff history again and it had zeros (non-scientific) between 26th and 23rd. This is consistent with the first PR being merged. Otherwise it has always been scientific notation

**Pull request merged**
